name: examples
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Restore cache
        id: cache-ql
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.roswell
            /home/runner/.cache/common-lisp
          key: ${{ runner.os }}-ql
      - name: Install Roswell
        env:
          LISP: sbcl-bin/2.4.0
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
      - name: Install env
        if: steps.cache-ql.outputs.cache-hit != 'true'
        run: |
          ros run -- --noinform \
               --eval '(ql-dist:install-dist "http://dist.shirakumo.org/shirakumo.txt" :prompt NIL)' \
               --non-interactive
      - uses: actions/checkout@v1
      - name: Build the library
        run: |
          ros run -- --noinform --dynamic-space-size 4Gb \
               --eval "(push \"$GITHUB_WORKSPACE\" ql:*local-project-directories*)" \
               --eval '(ql:quickload :trial-examples)' \
               --non-interactive
      - name: Build the binary
        run: |
          ros run -- --noinform --dynamic-space-size 4Gb \
               --eval "(push \"$GITHUB_WORKSPACE\" ql:*local-project-directories*)" \
               --eval '(asdf:make :trial-examples)' \
               --non-interactive
      - name: Make release ZIP
        run: |
          cd examples/bin/ && zip -r /tmp/trial-examples-{{ runner.os }}.zip *
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trial-examples-{{ runner.os }}
          path: /tmp/trial-examples-{{ runner.os }}.zip
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        continue-on-error: true
        with:
          allowUpdates: true
          name: Release ${{ github.ref_name }}
          artifacts: /tmp/trial-examples-{{ runner.os }}.zip
